// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MVSErunMCMC_RhoEtaAlpha
NumericMatrix MVSErunMCMC_RhoEtaAlpha(String model_category, unsigned int iter, Rcpp::NumericVector& init, Rcpp::NumericVector& gauJump, Rcpp::DataFrame& mvse_data, Rcpp::StringVector& prior_dists, Rcpp::List& prior_pars, double prior_mosq_biting_freq_mean);
RcppExport SEXP _MVSE_MVSErunMCMC_RhoEtaAlpha(SEXP model_categorySEXP, SEXP iterSEXP, SEXP initSEXP, SEXP gauJumpSEXP, SEXP mvse_dataSEXP, SEXP prior_distsSEXP, SEXP prior_parsSEXP, SEXP prior_mosq_biting_freq_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type model_category(model_categorySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type init(initSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type gauJump(gauJumpSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type mvse_data(mvse_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector& >::type prior_dists(prior_distsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type prior_pars(prior_parsSEXP);
    Rcpp::traits::input_parameter< double >::type prior_mosq_biting_freq_mean(prior_mosq_biting_freq_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(MVSErunMCMC_RhoEtaAlpha(model_category, iter, init, gauJump, mvse_data, prior_dists, prior_pars, prior_mosq_biting_freq_mean));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MVSE_MVSErunMCMC_RhoEtaAlpha", (DL_FUNC) &_MVSE_MVSErunMCMC_RhoEtaAlpha, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_MVSE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
