# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.MVSErunMCMC_RhoEtaAlpha <- function(model_category, iter, init, gauJump, mvse_data, prior_dists, prior_pars, prior_mosq_biting_freq_mean) {
    .Call('_MVSE_MVSErunMCMC_RhoEtaAlpha', PACKAGE = 'MVSE', model_category, iter, init, gauJump, mvse_data, prior_dists, prior_pars, prior_mosq_biting_freq_mean)
}

